PYTHON=python3

.PHONY: clean

include Makefile_office_home_standard Makefile_office31 Makefile_officehome_imbalanced Makefile_visda

UNAME_N := $(shell uname -n)
datapath := /Newdisk/xiang/domain_adaptation
tensorboardpath := tensorboard
